import pytest

from app.community.handlers.fun import is_bro_detected


@pytest.mark.parametrize(
    "text,expected",
    [
        ("бро", True),
        ("bro", True),
        ("B R O", True),
        ("б р о", True),
        ("б.р.о", True),
        ("br0", True),
        ("6ro", True),
        ("БРО", True),
        ("brrooo", True),
        ("hey bro!", True),
        ("ти шо, бро?", True),
        ("b_r_o", True),
        ("B.R.O", True),
        ("6r0", True),
        ("bro!", True),
        ("!bro", True),
        ("bro bro", True),
        ("BR0", True),
        ("б-р-о", True),
        ("brо", True),
        ("ЬRО", True),
        ("vro", True),
        ("𝐛𝐫𝐨", True),
        ("ｂｒｏ", True),
        ("bｒo", True),
        ("b\u0433o", True),
        ("бpo", True),
        ("wro", True),
        ("bru", True),
        ("bruuu", True),
        ("þro", True),
        ("brθ", True),
        ("бRяo", True),
        ("b.r.u", True),
        ("w_r_u", True),
        ("b | r | o", True),
        ("б'ро", True),
        ("ъro", True),
        ("ЪРО", True),
        ("вро", True),
        ("ßro", True),
        ("bρo", True),
        ("brο", True),
        ("brø", True),
        ("br@", True),
        ("brQ", True),
        ("brΘ", True),
        ("bЯo", True),
        ("|3ro", True),
        ("13ro", True),
        ("br()", True),
        ("br[]", True),
        ("br{}", True),
        ("br{)", True),
        ("br( ]", True),
        ("br( )", True),
        ("|)ro", True),
        ("b|2o", True),
        ("bl2o", True),
        ("br(.)", True),
        ("br[.]", True),
        ("|)ɹ()", True),
        ("𝕓𝕣𝕠", True),
        ("𝓫𝓻𝓸", True),
        ("𝔟𝔯𝔬", True),
        ("b\nr\no", True),
        ("B   R   O", True),
        ("🅱️r🅾️", True),
        ("\u202eorb", True),
        ("b\u200br\u200bo", True),
        ("b\u00adr\u00ado", True),
        ("br\u0308o", True),
        ("b२o", True),
        ("B|२o", True),
        ("🇧 🇷 🇴", True),
        ("br🔴", True),
        ("ѣro", True),
        ("ћro", True),
        ("brѳ", True),
        ("dobro", False),
        ("добро", False),
        ("striebro", False),
        ("obrovský", False),
        ("бронежилет", False),
        ("амброзія", False),
        ("бра", False),
        ("бор", False),
        ("брокер", False),
        ("бродяга", False),
        ("embro", False),
        ("ubro", False),
        ("robro", False),
        ("brutto", False),
        ("brother", False),
        ("brown", False),
        ("brow", False),
        ("брови", False),
        ("броня", False),
        ("броду", False),
        ("бросок", False),
        ("embryo", False),
        ("об'єкт", False),
        ("роз'єм", False),
        ("евро", False),
    ],
)
def test_is_bro_detected(text, expected):
    assert is_bro_detected(text) == expected
